#!/bin/bash
#
# Install / uninstall the SrvWatch LaunchAgent so it runs on boot and
# restarts automatically (KeepAlive).
#
#   ./deploy/install-launchd.sh install     # install + start now
#   ./deploy/install-launchd.sh uninstall   # stop + remove
#
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(dirname "$HERE")"

LABEL="com.srvwatch"
SCRIPT="$ROOT/srvwatch.py"
PLIST="$HOME/Library/LaunchAgents/${LABEL}.plist"
LOG="$HOME/Library/Logs/SrvWatch.log"

FB_LABEL="com.srvwatch.fail2ban"
FB_HELPER="$ROOT/deploy/fail2ban-status.py"
FB_PLIST="/Library/LaunchDaemons/${FB_LABEL}.plist"
FB_DIR="$HOME/Library/Logs/SrvWatch"
FB_STATUS="$FB_DIR/fail2ban-status.json"
FB_LOG="$FB_DIR/fail2ban-helper.log"

# Resolve an interpreter, preferring a real Python 3.
if [ -x /usr/bin/python3 ]; then
    PYTHON=/usr/bin/python3
elif command -v python3 >/dev/null 2>&1; then
    PYTHON="$(command -v python3)"
else
    echo "error: no python3 found" >&2
    exit 1
fi

# PATH must include /opt/homebrew/bin (for macmon) and $HOME/bin (for aqi.sh/clloc).
PATH_ENV="$HOME/bin:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"

render() {
    cat <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<!-- Generated by deploy/install-launchd.sh — do not edit by hand. -->
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>${LABEL}</string>

    <key>ProgramArguments</key>
    <array>
        <string>${PYTHON}</string>
        <string>${SCRIPT}</string>
    </array>

    <key>UserName</key>
    <string>$(id -un)</string>

    <key>WorkingDirectory</key>
    <string>${ROOT}</string>

    <key>EnvironmentVariables</key>
    <dict>
        <key>HOME</key>
        <string>${HOME}</string>
        <key>PATH</key>
        <string>${PATH_ENV}</string>
        <key>LANG</key>
        <string>en_US.UTF-8</string>
        <key>LC_ALL</key>
        <string>en_US.UTF-8</string>
        <key>PYTHONUNBUFFERED</key>
        <string>1</string>
    </dict>

    <key>RunAtLoad</key>
    <true/>

    <!-- Restart whenever it stops, for any reason. -->
    <key>KeepAlive</key>
    <true/>

    <key>StandardOutPath</key>
    <string>${LOG}</string>
    <key>StandardErrorPath</key>
    <string>${LOG}</string>
</dict>
</plist>
EOF
}

render_fail2ban() {
    cat <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<!-- Generated by deploy/install-launchd.sh — do not edit by hand. -->
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>${FB_LABEL}</string>

    <key>ProgramArguments</key>
    <array>
        <string>/usr/bin/python3</string>
        <string>${FB_HELPER}</string>
        <string>${FB_STATUS}</string>
    </array>

    <key>UserName</key>
    <string>root</string>

    <key>RunAtLoad</key>
    <true/>

    <!-- Refresh the fail2ban snapshot every 60 seconds. -->
    <key>StartInterval</key>
    <integer>60</integer>

    <key>StandardOutPath</key>
    <string>${FB_LOG}</string>
    <key>StandardErrorPath</key>
    <string>${FB_LOG}</string>
</dict>
</plist>
EOF
}

case "${1:-install}" in
    render)
        render
        ;;
    install)
        mkdir -p "$HOME/Library/LaunchAgents"
        render > "$PLIST"
        launchctl unload "$PLIST" 2>/dev/null || true
        launchctl load "$PLIST"
        IP="$(ipconfig getifaddr en0 2>/dev/null || true)"
        echo "Installed ${LABEL}"
        echo "  plist: ${PLIST}"
        echo "  log:   ${LOG}"
        echo "  view:  http://${IP:-<IP>}:9001"
        ;;
    uninstall)
        launchctl unload "$PLIST" 2>/dev/null || true
        rm -f "$PLIST"
        echo "Uninstalled ${LABEL}"
        ;;
    install-fail2ban)
        # Optional: export fail2ban jail/ban counts for the dashboard. Needs
        # root, since the fail2ban socket is root-only. Re-run after edits.
        mkdir -p "$FB_DIR"
        render_fail2ban | sudo tee "$FB_PLIST" >/dev/null
        sudo chown root:wheel "$FB_PLIST"
        sudo chmod 644 "$FB_PLIST"
        sudo launchctl bootout system/"$FB_LABEL" 2>/dev/null || true
        sudo launchctl bootstrap system "$FB_PLIST"
        sudo launchctl enable system/"$FB_LABEL" 2>/dev/null || true
        echo "Installed ${FB_LABEL} (refreshes every 60s)"
        echo "  plist:  ${FB_PLIST}"
        echo "  status: ${FB_STATUS}"
        ;;
    uninstall-fail2ban)
        sudo launchctl bootout system/"$FB_LABEL" 2>/dev/null || true
        sudo rm -f "$FB_PLIST" "$FB_STATUS"
        echo "Uninstalled ${FB_LABEL}"
        ;;
    *)
        echo "usage: $0 [install|uninstall|install-fail2ban|uninstall-fail2ban]" >&2
        exit 1
        ;;
esac
